openapi: "3.0.3"
info:
  title: "Subsistema 5: Gestión y emisión de facturas"
  version: "1.0.0"
  description: "Asignatura AOS: grupo 8"
  license:
    name: AOSGrupo8
    url: 'aaa'
  contact:
    name: Arquitecturas Orientadas a Servicios
    url: 'aaa'
    email: aaaaa@aaa.com
servers:
  - url: '{schema}://{server}:{port}/{basePath}'
    description: Servidor local
    variables:
      schema:
        description: Esquema
        default: http
        enum:
          - http
          - https
      server:
        description: Nombre del servidor
        default: 127.0.0.1
      port:
        description: Número de puerto
        default: '80'
      basePath:
        description: Ruta base
        default: api/v1
paths:
  /facturas:
    get:
      tags:
        - 'Facturas'
      summary: Devuelve todas las facturas existentes
      description: Devuelve todas las facturas del sistema
      operationId: api_facturas_cget
      responses:
        '200':
          description: Array de facturas
          content:
            application/json:
              schema:
                type: object
                properties:
                  facturas:
                    description: Array de facturas
                    type: array
                    items:
                      $ref: '#/components/schemas/Factura'
    post: 
      tags: 
        - 'Facturas'
      summary: Crea una factura.
      description: Crea una nueva factura
      operationId: api_facturas_post
      security:
        - MiWApiSecurity:
            - writer
      requestBody:
        $ref: '#/components/requestBodies/FacturaRequestBody'
      responses:
        '201':
          description: '`Created`: Factura created'
          links:
            GetFacturas:
              operationRef: '#/'
              parameters:
                idCliente: '$response.body#/idCliente'
              description: >
                El `id` devuelto por la petición puede ser usado como `facturaId` en `GET /facturas/{id]`
    options:
      tags:
        - 'Facturas'
      summary: Provides the list of HTTP supported methods.
      description: Return a `Allow` header with a comma separated list of HTTP supported methods.
      operationId: api_facturas_coptions
      responses:
        '204':
          description: '`Allow` header &lt;Response body is empty&gt;'
  /facturas/{id}: 
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags:
        - 'Facturas'
      summary: Devuelve una factura tras especificar su ID.
      description: Devuelve una factura tras especificar su `ID`.
      operationId: api_facturas_get
      security:
        - MiWApiSecurity:
            - reader
      responses:
        '200':
          description: Devolvemos un objeto del tipo factura
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
    put:
      tags:
        - 'Facturas'
      summary: Updates 
      description: Actualiza la factura tras pasar su `facturaId`.
      operationId: api_facturas_put
      responses:
        '200':
          description: Factura
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
      security:
        - MiWApiSecurity:
            - writer
    delete:
      tags:
        - 'Facturas'
      summary: Elimina el recurso Factura.
      description: Elimina el recurso Factura tras especificar su `facturaId`.
      operationId: api_facturas_delete
      security:
        - MiWApiSecurity:
            - writer
      responses:
        '204':
          description: Factura deleted &lt;Response body is empty&gt;
    options:
      tags:
        - 'Facturas'
      summary: Provides the list of HTTP supported methods.
      description: Return a `Allow` header with a comma separated list of HTTP supported methods.
      operationId: api_facturas_options_id
      responses:
        '204':
          description: '`Allow` header &lt;Response body is empty&gt;'         
  /clientes/{id}/facturas/:
    parameters:
    - $ref: '#/components/parameters/idCliente'

    get:
        tags:
          - 'Clientes'
        summary: Devuelve todas las facturas de un cliente.
        description: Dado un idCliente, devuelve todas sus facturas.
        operationId: api_facturas_get
        security:
          - MiWApiSecurity:
              - reader
        responses:
          '200':
            description: Array de facturas
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    facturas:
                      description: Factura array
                      type: array
                      items:
                        $ref: '#/components/parameters/id'




components:
  securitySchemes: {}
  schemas:
    HTTP_Problem:
      $ref: './schemas/http_problem.yml'
    Factura:
      type: object
      description: Contenido de una factura
      properties:
        facturaId:
          description: Identificador de la factura
          readOnly: True
          type: integer
          format: int32
        idCliente:
          description: ID del cliente propietario del vehículo
          type: integer
          format: int32
        Conceptos:
          description: Contenido de una factura
          type: array
          items:
            $ref: '#/components/schemas/Trabajo'
        fechaEmision:
          description: Fecha de emisión de la factura
          type: string
          format: date-time
        importe:
          type: integer
          format: int32
        links:
          description: Enlaces de relación
          type: object
          properties:
            trabajos:
              $ref: './Link.yml#/Link'
            self:
              $ref: './Link.yml#/Link'
      example:
        Factura:
        - facturaId: 1
          idCliente: 1
          Conceptos: 
            Trabajo:
              - trabajoId: 11
                idVehiculo: 3
                idCliente: 1
                nombre: Cambio de ruedas 
                descripcion: Cambio de ruedas debido al desgaste
                estadoTrabajo: Terminado
                fechaInicio: "2022/2/1"
                fechaFin: "2022/2/1"
              - trabajoId: 12
                idVehiculo: 3
                idCliente: 1
                nombre: Cambio de aceite 
                descripcion: El aceite ha sido cambiado por otro nuevo para evitar problemas en el motor. 
                estadoTrabajo: Terminado
                fechaInicio: "2022/2/1"
                fechaFin: "2022/2/1"
          fechaEmision: "2022/2/2"
          importe: 200
        
    Trabajo:
      type: object
      description: Añadir descripción 
      properties:
        trabajoId:
          description: Identificador del trabajo
          type: integer
          format: int32
        idVehiculo:
          description: ID del vehículo sobre el que se reliza el trabajo
          type: integer
          format: int32
        idCliente:
          description: ID del cliente propietario del vehículo
          type: integer
          format: int32
        nombre:
          description: Nombre del tipo de trabajo
          type: string
        descripcion:
          description: Descripción del trabajo
          type: string
        estadoTrabajo:
          description: Posibles estados del trabajo [Creado, Planificado, Iniciado, Terminado]
          type: string
          enum:
          - "Creado"
          - "Planificado"
          - "Iniciado"
          - "Terminado"    
        fechaInicio:
          description: Fecha en la que se inicializa el trabajo
          type: string
          format: date-time
        fechaFin:
          description: Fecha en la que se finaliza el trabajo
          type: string
          format: date-time
      x-last-modified: 1648662408321
  headers: {}
  responses:
    '200':
      description: Operación exitosa
      x-last-modified: 1648661433969
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Factura'
    Response_404:
      description: '`NOT FOUND`: recurso no disponible'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-404:
              $ref: '#/components/examples/response-http-404'
    Response_412:
      description: '`PRECONDITION FAILED`: El ETag proporcionado no está actualizado'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-412:
              $ref: '#/components/examples/response-http-412'
    Response_422:
      description: >
        `UNPROCESSABLE ENTITY`
        Falta alguno de los atributos obligatorios (`nombre`, `empresa`, `version` o `año_publicación`)
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-422:
              $ref: '#/components/examples/response-http-422'
  parameters:
    id:
      in: path
      name: id
      description: |-
        **ID**. 
         ID de la factura. 
         La API responde con la factura.
        type: number
        format: uuid
      x-last-modified: 1648661309447
      required: true
      deprecated: false
    idCliente:
      in: path
      name: idCliente
      description: |-
        **ID**. 
         ID del cliente. 
        type: number
        format: uuid
      x-last-modified: 1648661309447
      required: true
      deprecated: false
  requestBodies:
    FacturaRequestBody:
      description: 'Datos de la `Factura`'
      required: true
      content:
        application/json:
          schema:
            type: object
            $ref: '#/components/schemas/Factura'
    deleteFacturaRequestBody:
      description: 'Informacion para el borrado de la `Factura`'
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              idFactura:
                description: ID de la factura que se desea borrar
                type: integer

    updateFacturaRequestBody:
      description: 'Informacion para la actualizacion de la `Factura`'
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              idFactura:
                description: ID de la factura que se desea borrar
                type: integer
  examples:
    facturas:
      value:
        - facturaId: 1
          idCliente: 1
          Conceptos: 
            Trabajo:
              - trabajoId: 11
                idVehiculo: 3
                idCliente: 1
                nombre: Cambio de ruedas 
                descripcion: Cambio de ruedas debido al desgaste
                estadoTrabajo: Terminado
                fechaInicio: "2022/2/1"
                fechaFin: "2022/2/1"
              - trabajoId: 12
                idVehiculo: 3
                idCliente: 1
                nombre: Cambio de aceite 
                descripcion: El aceite ha sido cambiado por otro nuevo para evitar problemas en el motor. 
                estadoTrabajo: Terminado
                fechaInicio: "2022/2/1"
                fechaFin: "2022/2/1"
          fechaEmision: "2022/2/2"
          importe: 200

        - facturaId: 2
          idCliente: 2
          Conceptos: 
            Trabajo:
              - trabajoId: 14
                idVehiculo: 5
                idCliente: 2
                nombre: Cambio de bombillas 
                descripcion: Se han sustituido las bombillas que estaban fundidas en el vehículo.
                estadoTrabajo: Terminado
                fechaInicio: "2022/3/1"
                fechaFin: "2022/3/1"
              - trabajoId: 15
                idVehiculo: 5
                idCliente: 2
                nombre: Sustitución de brazos de suspensión 
                descripcion: Los brazos han sido sustituidos por otros nuevos para mejorar la suspensión del vehículo. 
                estadoTrabajo: Terminado
                fechaInicio: "2022/3/2"
                fechaFin: "2022/3/2"
          fechaEmision: "2022/3/2"
          importe: 500

        - facturaId: 3
          idCliente: 3
          Conceptos: 
            Trabajo:
              - trabajoId: 20
                idVehiculo: 6
                idCliente: 3
                nombre: Cambio de frenos 
                descripcion: Los discos de freno estaban desgastados y han sido sustituidos por otros nuevos
                estadoTrabajo: Terminado
                fechaInicio: "2022/3/5"
                fechaFin: "2022/3/5"
              - trabajoId: 21
                idVehiculo: 6
                idCliente: 3
                nombre: Freno de mano destensado
                descripcion: Se ha procedido a tensar de nuevo el freno de mano  
                estadoTrabajo: Terminado
                fechaInicio: "2022/3/5"
                fechaFin: "2022/3/5"
          fechaEmision: "2022/3/5"
          importe: 350

    response-http-400:
        value:
          type: https://httpstatuses.com/400
          title: BAD REQUEST
          status: 400
          detail: El servidor no puede procesar la peticion debido a que se ha percibido un error en el cliente.
          instance: about:blank
    response-http-404:
        value:
          type: https://httpstatuses.com/404
          title: NOT FOUND
          status: 404
          detail: El recurso solicitado no está disponible.
          instance: about:blank
    response-http-412:
        value:
          type: https://httpstatuses.com/412
          title: PRECONDITION FAILED
          status: 412
          detail: El ETag proporcionado no está actualizado
          instance: about:blank

    response-http-422:
        value:
          type: https://httpstatuses.com/422
          title: UNPROCESSABLE ENTITY
          status: 422
          detail: Falta alguno de los atributos obligatorios (nombre, empresa, version o año_publicación)
          instance: about:blank



