openapi: "3.0.3"
info:
  title: "Subsistema 5: Gestión y emisión de facturas"
  version: "1.0.0"
  description: "Asignatura AOS: grupo 8"
  license:
    name: AOSGrupo8
    url: 'aaa'
  contact:
    name: Arquitecturas Orientadas a Servicios
    url: 'aaa'
    email: aaaaa@aaa.com
servers:
  - url: '{schema}://{server}:{port}/{basePath}'
    description: Servidor local
    variables:
      schema:
        description: Esquema
        default: http
        enum:
          - http
          - https
      server:
        description: Nombre del servidor
        default: 127.0.0.1
      port:
        description: Número de puerto
        default: '80'
      basePath:
        description: Ruta base
        default: api/v1
paths:
  /facturas:
    get:
      tags:
        - 'Facturas'
      summary: Devuelve todas las facturas existentes
      description: Devuelve todas las facturas del sistema
      operationId: api_facturas_cget
      responses:
        '200':
          description: Array de facturas
          content:
            application/json:
              schema:
                type: object
                properties:
                  facturas:
                    description: Array de facturas
                    type: array
                    items:
                      $ref: './schemas/Factura.yml#/Factura'
              examples:
                facturaExamples:
                  $ref: './schemas/examples.yml#/examples/facturas'
    post:  
      tags: 
        - 'Facturas'
      summary: Crea una factura.
      description: Crea una nueva factura
      operationId: api_facturas_post
      security:
        - MiWApiSecurity:
            - writer
      requestBody:
        $ref: '#/components/requestBodies/FacturaRequestBody'
      responses:
        '201':
          description: '`Created`: Factura created'
          links:
            GetFacturas:
              operationRef: '#/'
              parameters:
                idCliente: '$response.body#/idCliente'
              description: >
                El `id` devuelto por la petición puede ser usado como `facturaId` en `GET /facturas/{id]`
    options:
      tags:
        - 'Facturas'
      summary: Provides the list of HTTP supported methods.
      description: Return a `Allow` header with a comma separated list of HTTP supported methods.
      operationId: api_facturas_coptions
      responses:
        '204':
          description: '`Allow` header &lt;Response body is empty&gt;'
  /facturas/{id}: 
    parameters:
      - $ref: '#/components/parameters/idfactura'
    get:
      tags:
        - 'Facturas'
      summary: Devuelve una factura tras especificar su ID.
      description: Devuelve una factura tras especificar su `ID`.
      operationId: api_facturas_get
      security:
        - MiWApiSecurity:
            - reader
      responses:
        '200':
          description: Devolvemos un objeto del tipo factura
          content:
            application/json:
              schema:
                $ref: './schemas/Factura.yml#/Factura'
    put:
      tags:
        - 'Facturas'
      summary: Updates 
      description: Actualiza la factura tras pasar su `facturaId`.
      operationId: api_facturas_put
      responses:
        '200':
          description: Factura
          content:
            application/json:
              schema:
                $ref: './schemas/Factura.yml#/Factura'
      security:
        - MiWApiSecurity:
            - writer
    delete:
      tags:
        - 'Facturas'
      summary: Elimina el recurso Factura.
      description: Elimina el recurso Factura tras especificar su `facturaId`.
      operationId: api_facturas_delete
      security:
        - MiWApiSecurity:
            - writer
      responses:
        '204':
          description: Factura deleted &lt;Response body is empty&gt;
    options:
      tags:
        - 'Facturas'
      summary: Provides the list of HTTP supported methods.
      description: Return a `Allow` header with a comma separated list of HTTP supported methods.
      operationId: api_facturas_options_id
      responses:
        '204':
          description: '`Allow` header &lt;Response body is empty&gt;'         
  /clientes/{id}/facturas/:
    parameters:
    - $ref: '#/components/parameters/idCliente'

    get:
        tags:
          - 'Clientes'
        summary: Devuelve todas las facturas de un cliente.
        description: Dado un idCliente, devuelve todas sus facturas.
        operationId: api_facturas_get
        security:
          - MiWApiSecurity:
              - reader
        responses:
          '200':
            description: Array de facturas
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    facturas:
                      description: Factura array
                      type: array
                      items:
                        $ref: '#/components/parameters/idfactura'




components:
  securitySchemes: {}
  schemas:
    HTTP_Problem:
      $ref: './schemas/http_problem.yml' 
  headers: {}
  responses:
    '200':
      description: Operación exitosa
      x-last-modified: 1648661433969
      content:
        application/json:
          schema:
            $ref: './schemas/Factura.yml#/Factura'
    Response_404:
      description: '`NOT FOUND`: recurso no disponible'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-404:
              $ref: './schemas/examples.yml#/examples/response-http-404'
    Response_412:
      description: '`PRECONDITION FAILED`: El ETag proporcionado no está actualizado'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-412:
              $ref: './schemas/examples.yml#/examples/response-http-412'
    Response_422:
      description: >
        `UNPROCESSABLE ENTITY`
        Falta alguno de los atributos obligatorios (`nombre`, `empresa`, `version` o `año_publicación`)
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-422:
              $ref: './schemas/examples.yml#/examples/response-http-422'
  parameters:
    idfactura:
      in: path
      name: id
      description: |-
        **ID**. 
         ID de la factura. 
         La API responde con la factura.
        type: number
        format: uuid
      x-last-modified: 1648661309447
      required: true
      schema:
        type: integer
        pattern: ^\d+$
    idCliente:
      in: path
      name: idCliente
      description: |-
        **ID**. 
         ID del cliente. 
        type: number
        format: uuid
      x-last-modified: 1648661309447
      required: true
      schema:
        type: integer
        pattern: ^\d+$
  requestBodies:
    FacturaRequestBody:
      description: 'Datos de la `Factura`'
      required: true
      content:
        application/json:
          schema:
            type: object
            $ref: './schemas/Factura.yml#/Factura'
    deleteFacturaRequestBody:
      description: 'Informacion para el borrado de la `Factura`'
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              idFactura:
                description: ID de la factura que se desea borrar
                type: integer

    updateFacturaRequestBody:
      description: 'Informacion para la actualizacion de la `Factura`'
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              idFactura:
                description: ID de la factura que se desea borrar
                type: integer