# coding: utf-8

"""
    Subsistema 5: Gestión y emisión de facturas

    Asignatura AOS: grupo 8  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aosgrupo8@aos.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.clientes_api import ClientesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientesApi(unittest.TestCase):
    """ClientesApi unit test stubs"""

    def setUp(self):
        self.api = ClientesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_facturas_get(self):
        """Test case for api_facturas_get

        Devuelve todas las facturas de un cliente.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
