# coding: utf-8

"""
    Subsistema 5: Gestión y emisión de facturas

    Asignatura AOS: grupo 8  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aosgrupo8@aos.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.http_problem import HTTPProblem  # noqa: E501
from swagger_client.rest import ApiException


class TestHTTPProblem(unittest.TestCase):
    """HTTPProblem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHTTPProblem(self):
        """Test HTTPProblem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.http_problem.HTTPProblem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
