# coding: utf-8

"""
    Subsistema 5: Gestión y emisión de facturas

    Asignatura AOS: grupo 8  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aosgrupo8@aos.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.facturas_api import FacturasApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFacturasApi(unittest.TestCase):
    """FacturasApi unit test stubs"""

    def setUp(self):
        self.api = FacturasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_facturas_cget(self):
        """Test case for api_facturas_cget

        Devuelve todas las facturas existentes  # noqa: E501
        """
        pass

    def test_api_facturas_coptions(self):
        """Test case for api_facturas_coptions

        Provides the list of HTTP supported methods.  # noqa: E501
        """
        pass

    def test_api_facturas_delete(self):
        """Test case for api_facturas_delete

        Elimina el recurso Factura.  # noqa: E501
        """
        pass

    def test_api_facturas_get(self):
        """Test case for api_facturas_get

        Devuelve una factura tras especificar su ID.  # noqa: E501
        """
        pass

    def test_api_facturas_options_id(self):
        """Test case for api_facturas_options_id

        Provides the list of HTTP supported methods.  # noqa: E501
        """
        pass

    def test_api_facturas_post(self):
        """Test case for api_facturas_post

        Crea una factura.  # noqa: E501
        """
        pass

    def test_api_facturas_put(self):
        """Test case for api_facturas_put

        Actualiza una factura determinada especificando su identificador y los campos a actualizar  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
