version: "3"

services:

  facturas:
    image: eloz/grupo8facturas:api
    ports: 
      - "81:80"
    networks:
        - taller_api
  clientes:
    image: api
    ports: 
      - "82:80"
    networks:
        - taller_api
  vehiculos:
    image: esteban23/gestionvehiculosaos:v1
    ports: 
      - "83:5000"
    networks:
        - taller_api
  trabajos:
    image: api
    ports: 
      - "84:80"
    networks:
        - taller_api
  notificaciones:
    image: api
    ports: 
      - "85:80"
    networks:
        - taller_api
  logs:
    image: api
    ports: 
      - "86:80"
    networks:
        - taller_api
  recambios:
    image: ghcr.io/adrianja5/aos-implementacion-servicio-recambios
    ports: 
      - "87:8080"
    networks:
      - taller_api


networks:
  taller_api: