version: "3"

services:

  facturas:
    image: eloz/grupo8facturas:latest
    ports: 
      - "81:80"
    networks:
        - taller_api
  clientes:
    image: eloz/grupo8facturas:latest
    ports: 
      - "82:80"
    networks:
        - taller_api
  vehiculos:
    image: esteban23/gestionvehiculosaos:v1
    ports: 
      - "83:5000"
    networks:
        - taller_api
  trabajos:
    image: eloz/grupo8facturas:latest
    ports: 
      - "84:80"
    networks:
        - taller_api
  notificaciones:
    image: eloz/grupo8facturas:latest
    ports: 
      - "85:80"
    networks:
        - taller_api
  logs-backend:
        image: stoplight/prism:4
        container_name: log_mocks
        command: mock --cors -h 0.0.0.0 "/logs/openapi.yaml"
        ports:
          - 8081:4010
        volumes:
            - ./openapi_logs:/logs:ro
  logs-frontend:
        image: swaggerapi/swagger-ui:latest
        container_name: logs_ui
        ports:
            - 8000:8080
        environment:
            SWAGGER_JSON: /logs/openapi.yaml
        volumes:
            - ./openapi_logs:/logs:ro
  recambios:
    image: ghcr.io/adrianja5/aos-implementacion-servicio-recambios
    ports: 
      - "8080:4010"
    networks:
      - taller_api


networks:
  taller_api: