# coding: utf-8

# flake8: noqa
"""
    Subsistema 5: Gestión y emisión de facturas

    Asignatura AOS: grupo 8  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aosgrupo8@aos.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.factura import Factura
from swagger_client.models.factura_request_body import FacturaRequestBody
from swagger_client.models.http_problem import HTTPProblem
from swagger_client.models.trabajo import Trabajo
