apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: clientes-backend-claim0
  name: clientes-backend-claim0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  hostPath:
    path: "../Taller/openapi_clientes/"
status: {}
