apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: clientes-frontend
  name: clientes-frontend
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8080
  selector:
    io.kompose.service: clientes-frontend
status:
  loadBalancer: {}
