apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: clientes-frontend
  name: clientes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clientes-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: clientes-frontend
    spec:
      containers:
        - env:
            - name: SWAGGER_JSON
              value: /AOS/clientes.yaml
          image: swaggerapi/swagger-ui
          name: clientes-ui
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /AOS
              name: clientes-frontend-hostpath0
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /run/desktop/mnt/host/c/Users/Eduardo/AOS1/Taller/openapi_clientes
          name: clientes-frontend-hostpath0
status: {}
