apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: logs-frontend
  name: logs-frontend
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8080
  selector:
    io.kompose.service: logs-frontend
status:
  loadBalancer: {}
