apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: logs-backend
  name: logs-backend
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 4010
  selector:
    io.kompose.service: logs-backend
status:
  loadBalancer: {}
