apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: notificaciones
  name: notificaciones
spec:
  ports:
    - name: "7777"
      port: 7777
      targetPort: 5000
  selector:
    io.kompose.service: notificaciones
status:
  loadBalancer: {}
