apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: trabajos-frontend
  name: trabajos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trabajos-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f Taller/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: trabajos-frontend
    spec:
      containers:
        - env:
            - name: SWAGGER_JSON
              value: /api/swagger.yaml
          image: swaggerapi/swagger-ui
          name: trabajos-frontend
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /api
              name: trabajos-frontend-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: trabajos-frontend-claim0
          persistentVolumeClaim:
            claimName: trabajos-frontend-claim0
            readOnly: true
status: {}
