apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: trabajos-backend
  name: trabajos-backend
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 4010
  selector:
    io.kompose.service: trabajos-backend
status:
  loadBalancer: {}
