apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vehiculosmongo
  name: vehiculosmongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vehiculosmongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/taller-api: "true"
        io.kompose.service: vehiculosmongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: ss1
          image: mongo
          name: vehiculosmongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mongo
              name: db-data
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /run/desktop/mnt/host/c/Users/Eduardo/AOS1/Taller
          name: db-data
status: {}
