apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vehiculos-frontend
  name: vehiculos-frontend
spec:
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8080
  selector:
    io.kompose.service: vehiculos-frontend
status:
  loadBalancer: {}
