apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vehiculos-backend
  name: vehiculos-backend
spec:
  ports:
    - name: "4016"
      port: 4016
      targetPort: 4010
  selector:
    io.kompose.service: vehiculos-backend
status:
  loadBalancer: {}
