apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vehiculos-2
  name: vehiculos-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vehiculos-2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/taller-api: "true"
        io.kompose.service: vehiculos-2
    spec:
      containers:
        - image: albertoseijo/aos_grupo4_global:serviciovehiculos
          name: vehiculos-2
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
