apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vehiculos-2
  name: vehiculos-2
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8080
  selector:
    io.kompose.service: vehiculos-2
status:
  loadBalancer: {}
