apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Taller/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vehiculos-frontend
  name: vehiculos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vehiculos-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f Taller/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: vehiculos-frontend
    spec:
      containers:
        - env:
            - name: SWAGGER_JSON
              value: /aos/openapi.yaml
          image: swaggerapi/swagger-ui:latest
          name: vehicles-ui
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /aos
              name: vehiculos-frontend-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: vehiculos-frontend-claim0
          persistentVolumeClaim:
            claimName: vehiculos-frontend-claim0
            readOnly: true
status: {}
