/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.HTTPProblem;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-05-08T20:36:10.229245+02:00[Europe/Madrid]")
@Validated
public interface ClientesApi {

    @Operation(summary = "Devuelve todas las facturas de un cliente.", description = "Devuelve todas las facturas de un cliente.", tags={ "Clientes" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Array de facturas", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))),
        
        @ApiResponse(responseCode = "404", description = "NOT FOUND", content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = HTTPProblem.class))),
        
        @ApiResponse(responseCode = "412", description = "PRECONDITION FAILED", content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = HTTPProblem.class))),
        
        @ApiResponse(responseCode = "500", description = "The server encountered an unexpected condition that prevented it from fulfilling the request. ", content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = HTTPProblem.class))) })
    @RequestMapping(value = "/clientes/{idCliente}/facturas/",
        produces = { "application/json", "application/problem+json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> apiFacturasGet(@Pattern(regexp="^\\d+$") @Parameter(in = ParameterIn.PATH, description = "**ID**.   ID del cliente.  type: number format: uuid", required=true, schema=@Schema()) @PathVariable("idCliente") Integer idCliente);

}

